### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by zhzy0077** [EMERALD0874/Steam-Deck-Themes#49]
Editing files in steam deck is awkward and most people will only have one font. What do you think of this `custom.css`?

```css
@font-face {
  font-family: Custom;
  src: url("/themes_custom/Fonts/fonts/custom.ttf"), url("/themes_custom/Fonts/fonts/custom.otf") format("opentype");
}


@font-face {
  font-family: Custom;
  src: url("/themes_custom/Fonts/fonts/custom-bold.ttf"), url("/themes_custom/Fonts/fonts/custom-bold.otf") format("opentype");
  font-weight: bold;
}


* {
  font-family: Custom, serif !important;
}
```

So people only need to place fonts named as "custom.ttf" and "custom-bold.ttf" then select custom in the dropdown. Easier to maintain and easier to modify. 

If it looks good to you, I can send the PR.
