### ISSUE TITLE
SteamGridDB improvement suggestion for Round theme

### ISSUE THREAD

**Issue by rasitayaz** [EMERALD0874/Steam-Deck-Themes#84]
I rounded up image previews in SteamGridDB pages and flattened the backgrounds. Didn't want to bother with PR so I'm just leaving the CSS here:

```css
.BasicUI #sgdb-wrap #images-container .asset-box-wrap .image-wrap>.thumb,
.BasicUI .sgdb-modal-details .asset-box-wrap .image-wrap>.thumb {
  background: none !important;
  background-color: #3F4F5E !important;
  overflow: hidden;
  border-radius: var(--round-radius-size);
}

.BasicUI .sgdb-modal-details .asset-box-wrap .image-wrap,
.BasicUI #sgdb-wrap #images-container .asset-box-wrap .image-wrap {
  background: none;
}

.BasicUI #sgdb-wrap #images-container .asset-box-wrap .chips {
  margin-top: var(--round-radius-size);
}
```

Here's a quick before/after:

![20241214130628_1](https://github.com/user-attachments/assets/535f0294-f8be-46c8-ab70-7c7343d1a20f)
![20241214131739_1](https://github.com/user-attachments/assets/d945639b-be88-423b-86b3-159054378336)
![20241214130529_1](https://github.com/user-attachments/assets/70260803-def6-4c3a-b6d4-a8a2e900efdc)
![20241214131801_1](https://github.com/user-attachments/assets/095b09e9-48e6-44a4-914e-af144611acf7)

Let me know what you think.
